// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Notification.proto

package AndroidConnect;

public final class NotificationOuterClass {
  private NotificationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface NotificationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AndroidConnect.Notification)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional int32 NotificationParameters = 1;</code>
     */
    int getNotificationParameters();

    /**
     * <code>optional string text = 2;</code>
     */
    java.lang.String getText();
    /**
     * <code>optional string text = 2;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();

    /**
     * <code>optional string undertext = 3;</code>
     */
    java.lang.String getUndertext();
    /**
     * <code>optional string undertext = 3;</code>
     */
    com.google.protobuf.ByteString
        getUndertextBytes();

    /**
     * <code>optional string title = 4;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>optional string title = 4;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>optional string imageName = 5;</code>
     */
    java.lang.String getImageName();
    /**
     * <code>optional string imageName = 5;</code>
     */
    com.google.protobuf.ByteString
        getImageNameBytes();
  }
  /**
   * Protobuf type {@code AndroidConnect.Notification}
   */
  public  static final class Notification extends
      com.google.protobuf.GeneratedMessageLite<
          Notification, Notification.Builder> implements
      // @@protoc_insertion_point(message_implements:AndroidConnect.Notification)
      NotificationOrBuilder {
    private Notification() {
      text_ = "";
      undertext_ = "";
      title_ = "";
      imageName_ = "";
    }
    public static final int NOTIFICATIONPARAMETERS_FIELD_NUMBER = 1;
    private int notificationParameters_;
    /**
     * <code>optional int32 NotificationParameters = 1;</code>
     */
    public int getNotificationParameters() {
      return notificationParameters_;
    }
    /**
     * <code>optional int32 NotificationParameters = 1;</code>
     */
    private void setNotificationParameters(int value) {
      
      notificationParameters_ = value;
    }
    /**
     * <code>optional int32 NotificationParameters = 1;</code>
     */
    private void clearNotificationParameters() {
      
      notificationParameters_ = 0;
    }

    public static final int TEXT_FIELD_NUMBER = 2;
    private java.lang.String text_;
    /**
     * <code>optional string text = 2;</code>
     */
    public java.lang.String getText() {
      return text_;
    }
    /**
     * <code>optional string text = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(text_);
    }
    /**
     * <code>optional string text = 2;</code>
     */
    private void setText(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      text_ = value;
    }
    /**
     * <code>optional string text = 2;</code>
     */
    private void clearText() {
      
      text_ = getDefaultInstance().getText();
    }
    /**
     * <code>optional string text = 2;</code>
     */
    private void setTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      text_ = value.toStringUtf8();
    }

    public static final int UNDERTEXT_FIELD_NUMBER = 3;
    private java.lang.String undertext_;
    /**
     * <code>optional string undertext = 3;</code>
     */
    public java.lang.String getUndertext() {
      return undertext_;
    }
    /**
     * <code>optional string undertext = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUndertextBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(undertext_);
    }
    /**
     * <code>optional string undertext = 3;</code>
     */
    private void setUndertext(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      undertext_ = value;
    }
    /**
     * <code>optional string undertext = 3;</code>
     */
    private void clearUndertext() {
      
      undertext_ = getDefaultInstance().getUndertext();
    }
    /**
     * <code>optional string undertext = 3;</code>
     */
    private void setUndertextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      undertext_ = value.toStringUtf8();
    }

    public static final int TITLE_FIELD_NUMBER = 4;
    private java.lang.String title_;
    /**
     * <code>optional string title = 4;</code>
     */
    public java.lang.String getTitle() {
      return title_;
    }
    /**
     * <code>optional string title = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(title_);
    }
    /**
     * <code>optional string title = 4;</code>
     */
    private void setTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
    }
    /**
     * <code>optional string title = 4;</code>
     */
    private void clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
    }
    /**
     * <code>optional string title = 4;</code>
     */
    private void setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      title_ = value.toStringUtf8();
    }

    public static final int IMAGENAME_FIELD_NUMBER = 5;
    private java.lang.String imageName_;
    /**
     * <code>optional string imageName = 5;</code>
     */
    public java.lang.String getImageName() {
      return imageName_;
    }
    /**
     * <code>optional string imageName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getImageNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(imageName_);
    }
    /**
     * <code>optional string imageName = 5;</code>
     */
    private void setImageName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      imageName_ = value;
    }
    /**
     * <code>optional string imageName = 5;</code>
     */
    private void clearImageName() {
      
      imageName_ = getDefaultInstance().getImageName();
    }
    /**
     * <code>optional string imageName = 5;</code>
     */
    private void setImageNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      imageName_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (notificationParameters_ != 0) {
        output.writeInt32(1, notificationParameters_);
      }
      if (!text_.isEmpty()) {
        output.writeString(2, getText());
      }
      if (!undertext_.isEmpty()) {
        output.writeString(3, getUndertext());
      }
      if (!title_.isEmpty()) {
        output.writeString(4, getTitle());
      }
      if (!imageName_.isEmpty()) {
        output.writeString(5, getImageName());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (notificationParameters_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, notificationParameters_);
      }
      if (!text_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getText());
      }
      if (!undertext_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getUndertext());
      }
      if (!title_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getTitle());
      }
      if (!imageName_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getImageName());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static AndroidConnect.NotificationOuterClass.Notification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static AndroidConnect.NotificationOuterClass.Notification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static AndroidConnect.NotificationOuterClass.Notification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static AndroidConnect.NotificationOuterClass.Notification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static AndroidConnect.NotificationOuterClass.Notification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static AndroidConnect.NotificationOuterClass.Notification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static AndroidConnect.NotificationOuterClass.Notification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static AndroidConnect.NotificationOuterClass.Notification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static AndroidConnect.NotificationOuterClass.Notification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static AndroidConnect.NotificationOuterClass.Notification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AndroidConnect.NotificationOuterClass.Notification prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code AndroidConnect.Notification}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          AndroidConnect.NotificationOuterClass.Notification, Builder> implements
        // @@protoc_insertion_point(builder_implements:AndroidConnect.Notification)
        AndroidConnect.NotificationOuterClass.NotificationOrBuilder {
      // Construct using AndroidConnect.NotificationOuterClass.Notification.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional int32 NotificationParameters = 1;</code>
       */
      public int getNotificationParameters() {
        return instance.getNotificationParameters();
      }
      /**
       * <code>optional int32 NotificationParameters = 1;</code>
       */
      public Builder setNotificationParameters(int value) {
        copyOnWrite();
        instance.setNotificationParameters(value);
        return this;
      }
      /**
       * <code>optional int32 NotificationParameters = 1;</code>
       */
      public Builder clearNotificationParameters() {
        copyOnWrite();
        instance.clearNotificationParameters();
        return this;
      }

      /**
       * <code>optional string text = 2;</code>
       */
      public java.lang.String getText() {
        return instance.getText();
      }
      /**
       * <code>optional string text = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        return instance.getTextBytes();
      }
      /**
       * <code>optional string text = 2;</code>
       */
      public Builder setText(
          java.lang.String value) {
        copyOnWrite();
        instance.setText(value);
        return this;
      }
      /**
       * <code>optional string text = 2;</code>
       */
      public Builder clearText() {
        copyOnWrite();
        instance.clearText();
        return this;
      }
      /**
       * <code>optional string text = 2;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTextBytes(value);
        return this;
      }

      /**
       * <code>optional string undertext = 3;</code>
       */
      public java.lang.String getUndertext() {
        return instance.getUndertext();
      }
      /**
       * <code>optional string undertext = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUndertextBytes() {
        return instance.getUndertextBytes();
      }
      /**
       * <code>optional string undertext = 3;</code>
       */
      public Builder setUndertext(
          java.lang.String value) {
        copyOnWrite();
        instance.setUndertext(value);
        return this;
      }
      /**
       * <code>optional string undertext = 3;</code>
       */
      public Builder clearUndertext() {
        copyOnWrite();
        instance.clearUndertext();
        return this;
      }
      /**
       * <code>optional string undertext = 3;</code>
       */
      public Builder setUndertextBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUndertextBytes(value);
        return this;
      }

      /**
       * <code>optional string title = 4;</code>
       */
      public java.lang.String getTitle() {
        return instance.getTitle();
      }
      /**
       * <code>optional string title = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        return instance.getTitleBytes();
      }
      /**
       * <code>optional string title = 4;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        copyOnWrite();
        instance.setTitle(value);
        return this;
      }
      /**
       * <code>optional string title = 4;</code>
       */
      public Builder clearTitle() {
        copyOnWrite();
        instance.clearTitle();
        return this;
      }
      /**
       * <code>optional string title = 4;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTitleBytes(value);
        return this;
      }

      /**
       * <code>optional string imageName = 5;</code>
       */
      public java.lang.String getImageName() {
        return instance.getImageName();
      }
      /**
       * <code>optional string imageName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getImageNameBytes() {
        return instance.getImageNameBytes();
      }
      /**
       * <code>optional string imageName = 5;</code>
       */
      public Builder setImageName(
          java.lang.String value) {
        copyOnWrite();
        instance.setImageName(value);
        return this;
      }
      /**
       * <code>optional string imageName = 5;</code>
       */
      public Builder clearImageName() {
        copyOnWrite();
        instance.clearImageName();
        return this;
      }
      /**
       * <code>optional string imageName = 5;</code>
       */
      public Builder setImageNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setImageNameBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AndroidConnect.Notification)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new AndroidConnect.NotificationOuterClass.Notification();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          AndroidConnect.NotificationOuterClass.Notification other = (AndroidConnect.NotificationOuterClass.Notification) arg1;
          notificationParameters_ = visitor.visitInt(notificationParameters_ != 0, notificationParameters_,
              other.notificationParameters_ != 0, other.notificationParameters_);
          text_ = visitor.visitString(!text_.isEmpty(), text_,
              !other.text_.isEmpty(), other.text_);
          undertext_ = visitor.visitString(!undertext_.isEmpty(), undertext_,
              !other.undertext_.isEmpty(), other.undertext_);
          title_ = visitor.visitString(!title_.isEmpty(), title_,
              !other.title_.isEmpty(), other.title_);
          imageName_ = visitor.visitString(!imageName_.isEmpty(), imageName_,
              !other.imageName_.isEmpty(), other.imageName_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  notificationParameters_ = input.readInt32();
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  text_ = s;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  undertext_ = s;
                  break;
                }
                case 34: {
                  String s = input.readStringRequireUtf8();

                  title_ = s;
                  break;
                }
                case 42: {
                  String s = input.readStringRequireUtf8();

                  imageName_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (AndroidConnect.NotificationOuterClass.Notification.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:AndroidConnect.Notification)
    private static final AndroidConnect.NotificationOuterClass.Notification DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Notification();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static AndroidConnect.NotificationOuterClass.Notification getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Notification> PARSER;

    public static com.google.protobuf.Parser<Notification> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
